### ISSUE TITLE
Lien « Cliquez ici » déconseillé

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/nightly#10]
Les liens « Ici » et « Cliquez ici » font partie des mauvaises pratiques web.

**Comment by TheoChevalier** [comment]
Pour corriger le lien, éditer simplement ce fichier https://github.com/mozfr/nightly/blob/master/app/templates/home.html.twig#L12 (en local ou même depuis l’éditeur GitHub intégré)
